using System.Windows.Media;

namespace PieLauncher;

public class Nostrum_WPF_SVG : RH
{
    public static StreamGeometry SvgAchievements => Get<StreamGeometry>("SvgAchievements");
    public static StreamGeometry SvgAdd => Get<StreamGeometry>("SvgAdd");
    public static StreamGeometry SvgAddCircle => Get<StreamGeometry>("SvgAddCircle");
    public static StreamGeometry SvgAddUser => Get<StreamGeometry>("SvgAddUser");
    public static StreamGeometry SvgAddUsers => Get<StreamGeometry>("SvgAddUsers");
    public static StreamGeometry SvgAuto => Get<StreamGeometry>("SvgAuto");
    public static StreamGeometry SvgAwaken => Get<StreamGeometry>("SvgAwaken");
    public static StreamGeometry SvgBasket => Get<StreamGeometry>("SvgBasket");
    public static StreamGeometry SvgBlock => Get<StreamGeometry>("SvgBlock");
    public static StreamGeometry SvgBlurOff => Get<StreamGeometry>("SvgBlurOff");
    public static StreamGeometry SvgBlurOn => Get<StreamGeometry>("SvgBlurOn");
    public static StreamGeometry SvgChatMessage => Get<StreamGeometry>("SvgChatMessage");
    public static StreamGeometry SvgCheckAll => Get<StreamGeometry>("SvgCheckAll");
    public static StreamGeometry SvgCheckCircle => Get<StreamGeometry>("SvgCheckCircle");
    public static StreamGeometry SvgClose => Get<StreamGeometry>("SvgClose");
    public static StreamGeometry SvgCollapseAll => Get<StreamGeometry>("SvgCollapseAll");
    public static StreamGeometry SvgConfirm => Get<StreamGeometry>("SvgConfirm");
    public static StreamGeometry SvgCopy => Get<StreamGeometry>("SvgCopy");
    public static StreamGeometry SvgCrossedSwords => Get<StreamGeometry>("SvgCrossedSwords");
    public static StreamGeometry SvgDelegateLeader => Get<StreamGeometry>("SvgDelegateLeader");
    public static StreamGeometry SvgDisband => Get<StreamGeometry>("SvgDisband");
    public static StreamGeometry SvgDiscord => Get<StreamGeometry>("SvgDiscord");
    public static StreamGeometry SvgDotsVertical => Get<StreamGeometry>("SvgDotsVertical");
    public static StreamGeometry SvgDownArrow => Get<StreamGeometry>("SvgDownArrow");
    public static StreamGeometry SvgDrag => Get<StreamGeometry>("SvgDrag");
    public static StreamGeometry SvgExpandAll => Get<StreamGeometry>("SvgExpandAll");
    public static StreamGeometry SvgEye => Get<StreamGeometry>("SvgEye");
    public static StreamGeometry SvgFolder => Get<StreamGeometry>("SvgFolder");
    public static StreamGeometry SvgGift => Get<StreamGeometry>("SvgGift");
    public static StreamGeometry SvgGitHub => Get<StreamGeometry>("SvgGitHub");
    public static StreamGeometry SvgGuild => Get<StreamGeometry>("SvgGuild");
    public static StreamGeometry SvgHeart => Get<StreamGeometry>("SvgHeart");
    public static StreamGeometry SvgHide => Get<StreamGeometry>("SvgHide");
    public static StreamGeometry SvgInfo => Get<StreamGeometry>("SvgInfo");
    public static StreamGeometry SvgMail => Get<StreamGeometry>("SvgMail");
    public static StreamGeometry SvgMapMarker => Get<StreamGeometry>("SvgMapMarker");
    public static StreamGeometry SvgMatching => Get<StreamGeometry>("SvgMatching");
    public static StreamGeometry SvgMenuRight => Get<StreamGeometry>("SvgMenuRight");
    public static StreamGeometry SvgMinimize => Get<StreamGeometry>("SvgMinimize");
    public static StreamGeometry SvgMoney => Get<StreamGeometry>("SvgMoney");
    public static StreamGeometry SvgMove => Get<StreamGeometry>("SvgMove");
    public static StreamGeometry SvgOpenLink => Get<StreamGeometry>("SvgOpenLink");
    public static StreamGeometry SvgPaypal => Get<StreamGeometry>("SvgPaypal");
    public static StreamGeometry SvgPen => Get<StreamGeometry>("SvgPen");
    public static StreamGeometry SvgPin => Get<StreamGeometry>("SvgPin");
    public static StreamGeometry SvgQuestionMark => Get<StreamGeometry>("SvgQuestionMark");
    public static StreamGeometry SvgQuestLog => Get<StreamGeometry>("SvgQuestLog");
    public static StreamGeometry SvgReload => Get<StreamGeometry>("SvgReload");
    public static StreamGeometry SvgRemoveCircle => Get<StreamGeometry>("SvgRemoveCircle");
    public static StreamGeometry SvgRemoveUser => Get<StreamGeometry>("SvgRemoveUser");
    public static StreamGeometry SvgSearch => Get<StreamGeometry>("SvgSearch");
    public static StreamGeometry SvgSettings => Get<StreamGeometry>("SvgSettings");
    public static StreamGeometry SvgShare => Get<StreamGeometry>("SvgShare");
    public static StreamGeometry SvgShirt => Get<StreamGeometry>("SvgShirt");
    public static StreamGeometry SvgShop => Get<StreamGeometry>("SvgShop");
    public static StreamGeometry SvgSocial => Get<StreamGeometry>("SvgSocial");
    public static StreamGeometry SvgStar => Get<StreamGeometry>("SvgStar");
    public static StreamGeometry SvgTrophy => Get<StreamGeometry>("SvgTrophy");
    public static StreamGeometry SvgTwitch => Get<StreamGeometry>("SvgTwitch");
    public static StreamGeometry SvgUnpin => Get<StreamGeometry>("SvgUnpin");
    public static StreamGeometry SvgUpArrow => Get<StreamGeometry>("SvgUpArrow");
    public static StreamGeometry SvgUser => Get<StreamGeometry>("SvgUser");
    public static StreamGeometry SvgUserAdd => Get<StreamGeometry>("SvgUserAdd");
    public static StreamGeometry SvgUsers => Get<StreamGeometry>("SvgUsers");
    public static StreamGeometry SvgWarning => Get<StreamGeometry>("SvgWarning");
}